name = "hono-seo4j"
main = "src/index.ts"
compatibility_date = "2022-07-18"
workers_dev = true
node_compat = true

[vars]
URI = "neo4j+s://184de066.databases.neo4j.io"
USER = "neo4j"
PASSWORD = "lbOvDTYhK84D5zEIP90ULP5TYoHAMFNBTcLiB-jJ46o"